//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleSiteMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoute
    {
        public long RoutId { get; set; }
        public string PageType { get; set; }
        public string Slug { get; set; }
        public Nullable<long> Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
